version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.8-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  worker:
    build: .
    command: celery -A microslurm:celery_app worker --loglevel=info
    depends_on:
      - rabbitmq
      
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: microslurm
      POSTGRES_PASSWORD: microslurm
      POSTGRES_DB: microslurm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: